"""Ship stage — reads seo/ off disk and replaces main via GitHub Git Data API."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ..clients.github import GitHubClient
from ..models.insights import ActionItem


@dataclass
class ShipResult:
    commit_sha: str
    commit_url: str
    parent_sha: str
    files_published: list[str]


def _build_commit_message(
    run_id: str,
    parent_sha: str,
    action_items: list[ActionItem],
) -> str:
    item_lines = "\n".join(
        f"- {item.edit_type.value}: {item.rationale}" for item in action_items
    )
    return (
        "lovabletoseo: replace site with AI-discoverable static version\n\n"
        f"This commit replaces the original Lovable React source with a prerendered,\n"
        f"AEO-optimized static page generated by lovabletoseo (run {run_id}).\n\n"
        f"Action items applied:\n{item_lines}\n\n"
        f"The original React source is preserved in the parent commit:\n"
        f"{parent_sha}\n\n"
        "To revert this migration:\n"
        f"    git revert HEAD\n"
        "or to restore the exact source tree:\n"
        f"    git checkout {parent_sha} -- . && git commit -m 'revert: restore React source'"
    )


async def ship(
    repo_url: str,
    seo_dir: Path,
    run_id: str,
    action_items: list[ActionItem],
    github_token: str,
    push: bool = True,
) -> ShipResult:
    """
    Read all files under seo_dir, strip the 'seo/' prefix, and publish them
    at the root of main. Inserts the migration sentinel comment.
    """
    # Collect output files
    files: dict[str, bytes] = {}
    for p in sorted(seo_dir.rglob("*")):
        if p.is_file():
            rel = str(p.relative_to(seo_dir))
            files[rel] = p.read_bytes()

    if not files:
        raise RuntimeError(f"No files found in {seo_dir}")

    # Insert migration sentinel into index.html
    if "index.html" in files:
        html = files["index.html"].decode()
        # Get parent_sha placeholder (will be filled in after we read from GitHub)
        # Temporarily mark as pending — replaced below after we know parent_sha
        files["index.html"] = html.encode()

    if not push:
        return ShipResult(
            commit_sha="",
            commit_url="",
            parent_sha="",
            files_published=list(files.keys()),
        )

    client = GitHubClient(github_token)
    owner, repo = GitHubClient.parse_repo_url(repo_url)
    default_branch = await client.get_default_branch(owner, repo)
    parent_sha = await client.get_branch_sha(owner, repo, default_branch)

    # Inject sentinel with real parent_sha
    if "index.html" in files:
        html = files["index.html"].decode()
        sentinel = f"<!-- generated-by:lovabletoseo run={run_id} parent={parent_sha} -->"
        html = html.replace("<!doctype html>", f"<!doctype html>\n{sentinel}", 1)
        if sentinel not in html:
            html = sentinel + "\n" + html
        files["index.html"] = html.encode()

    commit_message = _build_commit_message(run_id, parent_sha, action_items)

    result = await client.publish_to_main(
        repo_url=repo_url,
        files=files,
        commit_message=commit_message,
        expected_parent_sha=parent_sha,
    )

    return ShipResult(
        commit_sha=result["commit_sha"],
        commit_url=result["commit_url"],
        parent_sha=parent_sha,
        files_published=list(files.keys()),
    )
