import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdir, writeFile, rm } from "node:fs/promises";
import { join, dirname } from "node:path";
import type { Site } from "./enhance.js";
import type { RepoMeta } from "./ingest.js";

const exec = promisify(execFile);

export type ShipResult = {
  branch: string;
  commitSha: string | null;
  prUrl: string | null;
  /** Files actually written, repo-relative. */
  written: string[];
};

async function writeSiteFiles(
  rootDir: string,
  mountPath: string,
  site: Site,
): Promise<string[]> {
  const written: string[] = [];
  for (const [rel, contents] of Object.entries(site.files)) {
    const target = join(rootDir, mountPath, rel);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, contents);
    written.push(join(mountPath, rel));
  }
  return written;
}

/**
 * Write the rebuilt site somewhere useful.
 *
 * - If `repo` is provided: write into a fresh branch on the cloned repo,
 *   commit, optionally push + open a PR.
 * - Otherwise: write into a flat `out/<run-id>/site/` directory.
 */
export async function ship(
  site: Site,
  opts: {
    repo?: RepoMeta;
    outDir: string;
    branch: string;
    runId: string;
    openPr: boolean;
    /** PR body — usually the strategist brief */
    prBody?: string;
  },
): Promise<ShipResult> {
  // Always write to outDir/site so the user has a clean local copy.
  const localSiteDir = join(opts.outDir, "site");
  await rm(localSiteDir, { recursive: true, force: true });
  const writtenLocal = await writeSiteFiles(opts.outDir, "site", site);

  if (!opts.repo) {
    return { branch: opts.branch, commitSha: null, prUrl: null, written: writtenLocal };
  }

  const cwd = opts.repo.path;
  await exec("git", ["checkout", "-b", opts.branch], { cwd });
  const writtenInRepo = await writeSiteFiles(cwd, site.mountPath, site);
  await exec("git", ["add", site.mountPath], { cwd });
  await exec(
    "git",
    [
      "commit",
      "-m",
      `lovabletoseo: SEO+GEO rebuild (run ${opts.runId})\n\nGenerated by lovabletoseo from ${opts.repo.remote ?? "local checkout"}.`,
    ],
    { cwd },
  );
  const { stdout: sha } = await exec("git", ["rev-parse", "HEAD"], { cwd });

  let prUrl: string | null = null;
  if (opts.openPr && opts.repo.remote) {
    await exec("git", ["push", "-u", "origin", opts.branch], { cwd });
    const body = opts.prBody ?? "Automated SEO+GEO rebuild by lovabletoseo.";
    const { stdout } = await exec(
      "gh",
      [
        "pr",
        "create",
        "--title",
        `lovabletoseo: SEO+GEO rebuild (${opts.runId})`,
        "--body",
        body,
        "--base",
        opts.repo.defaultBranch,
        "--head",
        opts.branch,
      ],
      { cwd },
    );
    prUrl = stdout.trim().split("\n").pop() ?? null;
  }

  return {
    branch: opts.branch,
    commitSha: sha.trim(),
    prUrl,
    written: writtenInRepo,
  };
}
