import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  type DiscoverResult,
  type Profile,
  type RunContext,
} from "../types/index.js";
import type { PeecSnapshot } from "./09-peec-snapshot.js";

// Generates `.agents/product-marketing-context.md` — the foundation file
// every marketing skill reads. Pre-populating it lets the skills run
// autonomously instead of asking the user 5-15 setup questions.
//
// Sourced from:
//   - profile (Tavily deep profile + Sonnet synthesis)
//   - discover.final (validated competitors)
//   - snapshot (Peec visibility/sentiment/citation data; may be empty
//     if Peec hasn't completed its 24h schedule yet)

function bullet(items: string[]): string {
  return items.length === 0 ? "_(none)_" : items.map((s) => `- ${s}`).join("\n");
}

function fmtPct(n: number | null): string {
  if (n == null) return "—";
  return `${(n * 100).toFixed(0)}%`;
}

function fmtMaybe(v: string | null | undefined): string {
  return v && v.trim() ? v : "_(unknown)_";
}

export async function contextFile(args: {
  ctx: RunContext;
  profile: Profile;
  discover: DiscoverResult;
  snapshot: PeecSnapshot;
}): Promise<string> {
  const { profile, discover, snapshot } = args;

  const competitorRows = discover.final
    .map((c) => {
      const name = c.canonical_name || c.name;
      const why = (c.why_relevant ?? c.validation_reason ?? "").replace(/\|/g, "/");
      return `| ${name} | ${c.domain} | ${why} |`;
    })
    .join("\n");

  const sc = snapshot.scorecard;
  const ownVis = fmtPct(sc.own?.visibility ?? null);
  const ownSov = fmtPct(sc.own?.share_of_voice ?? null);
  const ownSent = sc.own?.sentiment ?? null;
  const wins = snapshot.prompt_breakdown.filter((p) => p.winning_flag).slice(0, 5);
  const losses = snapshot.prompt_breakdown.filter((p) => p.weakness_flag).slice(0, 8);
  const engines = snapshot.engine_breakdown.slice(0, 5);
  const gapDomains = snapshot.gap_targets.domains.slice(0, 8);
  const gapUrls = snapshot.gap_targets.urls.slice(0, 8);
  const fanout = snapshot.fanout_queries.slice(0, 12);

  const md = `# Product Marketing Context — ${profile.name}

> Auto-generated by **lovabletoseo** at ${new Date().toISOString()}
> from Tavily deep profile + Peec snapshot. All marketing skills
> (site-architecture, copywriting, ai-seo, seo-audit, schema-markup,
> copy-editing, competitor-alternatives) reference this file.

## Brand

- **Name:** ${profile.name}
- **Domain:** ${profile.domain}
- **Tagline:** ${fmtMaybe(profile.tagline)}
- **What we do:** ${fmtMaybe(profile.occupation)}

## Category

- **Buyer-friendly category (what they Google):** ${fmtMaybe(profile.category_for_search)}
- **Industry:** ${fmtMaybe(profile.industry)}

## ICP — who buys this

- **Audience:** ${fmtMaybe(profile.audience)}
- **Sophistication:** ${fmtMaybe(profile.audience_sophistication)}
- **Target markets:** ${profile.target_markets.length ? profile.target_markets.join(", ") : "_(unknown)_"}

## Positioning & Voice

- **Brand presentation:** ${profile.brand_presentation.length ? profile.brand_presentation.join(", ") : "_(unknown)_"}
- **Pricing tier:** ${fmtMaybe(profile.pricing_tier)}
- **Scale tier:** ${fmtMaybe(profile.scale_tier)}

## Products & Services

${bullet(profile.products_and_services)}

## Differentiators

${bullet(profile.key_differentiators)}

## Competitive Landscape

${competitorRows.length ? `| Competitor | Domain | Why we compete |\n|---|---|---|\n${competitorRows}` : "_(competitor discovery returned no validated competitors)_"}

${profile.competitor_signals.length ? `**Competitors named in source material:** ${profile.competitor_signals.join(", ")}` : ""}

## AI Visibility — Peec snapshot

**Window:** ${snapshot.meta.date_range.start} → ${snapshot.meta.date_range.end} (${snapshot.meta.date_range.days} days)
**Coverage:** ${snapshot.meta.coverage.actual} / ${snapshot.meta.coverage.expected} chats (${(snapshot.meta.coverage.pct * 100).toFixed(0)}%)
**Active models:** ${snapshot.meta.active_models.join(", ") || "_(none)_"}

### Scorecard
- **Our visibility:** ${ownVis}
- **Share of voice:** ${ownSov}
- **Sentiment:** ${ownSent ?? "—"}
- **Rank:** ${sc.our_rank} of ${sc.total_brands_ranked} brands

### Where we WIN (own visibility ≥ 70% and ≥ top competitor)
${wins.length ? wins.map((w) => `- **${w.prompt_text || w.prompt_id}** — own=${fmtPct(w.own_visibility)} (top=${fmtPct(w.top_competitor_visibility)} from ${w.top_competitor || "—"})`).join("\n") : "_(no clear wins yet)_"}

### Where we LOSE (own visibility < 30% — top STRATEGY targets)
${losses.length ? losses.map((l) => `- **${l.prompt_text || l.prompt_id}** — own=${fmtPct(l.own_visibility)}, top=${fmtPct(l.top_competitor_visibility)} (${l.top_competitor || "—"})`).join("\n") : "_(none — visibility is uniform across prompts)_"}

### Per-engine gap (largest first)
${engines.length ? engines.map((e) => `- **${e.model}** — own=${fmtPct(e.own_visibility)}, top=${fmtPct(e.top_competitor_visibility)} (${e.top_competitor || "—"}), gap=${fmtPct(e.gap_pct)}`).join("\n") : "_(no engine data yet)_"}

## What the AIs are citing instead of us

### Top gap **domains** (cite competitors, not us)
${gapDomains.length ? gapDomains.map((d) => `- **${d.domain}** — class=${d.classification ?? "?"}, retrievals=${d.retrieval_count ?? 0}, cites: ${d.competitors_cited.slice(0, 3).join(", ") || "—"}`).join("\n") : "_(no gap domains)_"}

### Top gap **URLs**
${gapUrls.length ? gapUrls.map((u) => `- ${u.url} — ${u.title ?? ""} (cites: ${u.competitors_cited.slice(0, 3).join(", ") || "—"})`).join("\n") : "_(no gap URLs)_"}

## SEO/GEO targeting — buyer queries the AIs actually ran (fanout)

These are the strings the AI engines internally searched for to answer prompts.
Pure GEO targeting gold — copy the site to match these queries.

${fanout.length ? fanout.map((q) => `- \`${q.query}\` (used in ${q.count} chats)`).join("\n") : "_(no fanout data — Peec snapshot may be empty or chats not yet processed)_"}
`;

  const outPath = resolve(args.ctx.outDir, "product-marketing-context.md");
  await writeFile(outPath, md, "utf8");
  console.log(`[context] wrote ${md.length} bytes → ${outPath}`);
  return md;
}
