import {
  GitHubError,
  openPullRequest,
  pushBranchWithChanges,
} from "../clients/github.js";
import { type Inventory, type RunContext } from "../types/index.js";
import type { ApplyResult } from "./12-apply.js";

export type ShipResult = {
  branch: string;
  commitSha: string;
  prUrl: string | null;
  skipped?: string;
};

function shortJobId(ctx: RunContext): string {
  return ctx.jobId.replace(/-/g, "").slice(0, 8);
}

function buildCommitMessage(_apply: ApplyResult, summary: string | undefined): {
  subject: string;
  body: string;
} {
  return {
    subject: "lovabletoseo: SEO + GEO improvements",
    body:
      `Generated by lovabletoseo — fixes technical SEO + injects schema for ` +
      `AI engines (ChatGPT/Perplexity/Claude/Gemini) and search engines.\n\n` +
      (summary ? `${summary}\n\n` : "") +
      `Run-tracked changes:\n` +
      `- index.html shell: title + meta description + canonical + Open Graph + Twitter + JSON-LD\n` +
      `- public/robots.txt: allow-all + sitemap pointer\n` +
      `- public/sitemap.xml: covers all known routes\n\n` +
      `Component code unchanged — open in Lovable to keep iterating.`,
  };
}

function buildPrTitle(inventory: Inventory): string {
  const repoName = inventory.repoUrl.replace(/[/:]([^/]+)\.git$/, "$1").split("/").pop() ?? "site";
  return `lovabletoseo: SEO + GEO fixes for ${repoName}`;
}

export async function ship(args: {
  ctx: RunContext;
  inventory: Inventory;
  apply: ApplyResult;
  reportMd?: string;
  dryRun?: boolean;
}): Promise<ShipResult> {
  const { inventory, apply } = args;

  if (apply.changedFiles.length === 0 && apply.newFiles.length === 0) {
    console.log("[ship] no changes from APPLY — skipping push");
    return { branch: "", commitSha: "", prUrl: null, skipped: "no changes" };
  }

  if (args.dryRun) {
    console.log("[ship] dryRun=true — skipping push + PR");
    return { branch: "", commitSha: "", prUrl: null, skipped: "dry-run" };
  }

  const branch = `lovabletoseo/${shortJobId(args.ctx)}`;
  const message = buildCommitMessage(apply, undefined);
  console.log(`[ship] pushing branch ${branch}…`);

  let pushResult;
  try {
    pushResult = await pushBranchWithChanges({
      cwd: inventory.cloneDir,
      branch,
      commitMessage: message.subject,
      commitBody: message.body,
    });
  } catch (e) {
    if (e instanceof GitHubError) {
      console.error(`[ship] push failed (${e.code}): ${e.message}`);
      return { branch, commitSha: "", prUrl: null, skipped: `push failed: ${e.code}` };
    }
    throw e;
  }
  console.log(`[ship]   committed ${pushResult.commitSha.slice(0, 7)} on ${branch}`);

  console.log("[ship] opening PR…");
  let prUrl: string | null = null;
  try {
    const pr = await openPullRequest({
      cwd: inventory.cloneDir,
      base: inventory.defaultBranch || "main",
      head: branch,
      title: buildPrTitle(inventory),
      body: args.reportMd ?? message.body,
    });
    prUrl = pr.url || null;
    if (prUrl) console.log(`[ship]   PR: ${prUrl}`);
  } catch (e) {
    if (e instanceof GitHubError) {
      console.error(`[ship] PR create failed (${e.code}): ${e.message}`);
    } else {
      throw e;
    }
  }

  return { branch, commitSha: pushResult.commitSha, prUrl };
}
